/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavbarLayoutRouteImport } from './routes/_NavbarLayout/route'
import { Route as NavbarLayoutIndexImport } from './routes/_NavbarLayout/index'
import { Route as NavbarLayoutBreadcrumbsRouteImport } from './routes/_NavbarLayout/_breadcrumbs/route'
import { Route as NavbarLayoutBreadcrumbsReportsIndexImport } from './routes/_NavbarLayout/_breadcrumbs/reports/index'
import { Route as NavbarLayoutBreadcrumbsComplaintsIndexImport } from './routes/_NavbarLayout/_breadcrumbs/complaints/index'
import { Route as NavbarLayoutBreadcrumbsusersAgentsIndexImport } from './routes/_NavbarLayout/_breadcrumbs/(users)/agents/index'
import { Route as NavbarLayoutBreadcrumbsusersAgentsNewImport } from './routes/_NavbarLayout/_breadcrumbs/(users)/agents/new'

// Create/Update Routes

const NavbarLayoutRouteRoute = NavbarLayoutRouteImport.update({
  id: '/_NavbarLayout',
  getParentRoute: () => rootRoute,
} as any)

const NavbarLayoutIndexRoute = NavbarLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutRouteRoute,
} as any)

const NavbarLayoutBreadcrumbsRouteRoute =
  NavbarLayoutBreadcrumbsRouteImport.update({
    id: '/_breadcrumbs',
    getParentRoute: () => NavbarLayoutRouteRoute,
  } as any)

const NavbarLayoutBreadcrumbsReportsIndexRoute =
  NavbarLayoutBreadcrumbsReportsIndexImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => NavbarLayoutBreadcrumbsRouteRoute,
  } as any)

const NavbarLayoutBreadcrumbsComplaintsIndexRoute =
  NavbarLayoutBreadcrumbsComplaintsIndexImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => NavbarLayoutBreadcrumbsRouteRoute,
  } as any)

const NavbarLayoutBreadcrumbsusersAgentsIndexRoute =
  NavbarLayoutBreadcrumbsusersAgentsIndexImport.update({
    id: '/(users)/agents/',
    path: '/agents/',
    getParentRoute: () => NavbarLayoutBreadcrumbsRouteRoute,
  } as any)

const NavbarLayoutBreadcrumbsusersAgentsNewRoute =
  NavbarLayoutBreadcrumbsusersAgentsNewImport.update({
    id: '/(users)/agents/new',
    path: '/agents/new',
    getParentRoute: () => NavbarLayoutBreadcrumbsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_NavbarLayout': {
      id: '/_NavbarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_NavbarLayout/_breadcrumbs': {
      id: '/_NavbarLayout/_breadcrumbs'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarLayoutBreadcrumbsRouteImport
      parentRoute: typeof NavbarLayoutRouteImport
    }
    '/_NavbarLayout/': {
      id: '/_NavbarLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutIndexImport
      parentRoute: typeof NavbarLayoutRouteImport
    }
    '/_NavbarLayout/_breadcrumbs/complaints/': {
      id: '/_NavbarLayout/_breadcrumbs/complaints/'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof NavbarLayoutBreadcrumbsComplaintsIndexImport
      parentRoute: typeof NavbarLayoutBreadcrumbsRouteImport
    }
    '/_NavbarLayout/_breadcrumbs/reports/': {
      id: '/_NavbarLayout/_breadcrumbs/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof NavbarLayoutBreadcrumbsReportsIndexImport
      parentRoute: typeof NavbarLayoutBreadcrumbsRouteImport
    }
    '/_NavbarLayout/_breadcrumbs/(users)/agents/new': {
      id: '/_NavbarLayout/_breadcrumbs/(users)/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof NavbarLayoutBreadcrumbsusersAgentsNewImport
      parentRoute: typeof NavbarLayoutBreadcrumbsRouteImport
    }
    '/_NavbarLayout/_breadcrumbs/(users)/agents/': {
      id: '/_NavbarLayout/_breadcrumbs/(users)/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof NavbarLayoutBreadcrumbsusersAgentsIndexImport
      parentRoute: typeof NavbarLayoutBreadcrumbsRouteImport
    }
  }
}

// Create and export the route tree

interface NavbarLayoutBreadcrumbsRouteRouteChildren {
  NavbarLayoutBreadcrumbsComplaintsIndexRoute: typeof NavbarLayoutBreadcrumbsComplaintsIndexRoute
  NavbarLayoutBreadcrumbsReportsIndexRoute: typeof NavbarLayoutBreadcrumbsReportsIndexRoute
  NavbarLayoutBreadcrumbsusersAgentsNewRoute: typeof NavbarLayoutBreadcrumbsusersAgentsNewRoute
  NavbarLayoutBreadcrumbsusersAgentsIndexRoute: typeof NavbarLayoutBreadcrumbsusersAgentsIndexRoute
}

const NavbarLayoutBreadcrumbsRouteRouteChildren: NavbarLayoutBreadcrumbsRouteRouteChildren =
  {
    NavbarLayoutBreadcrumbsComplaintsIndexRoute:
      NavbarLayoutBreadcrumbsComplaintsIndexRoute,
    NavbarLayoutBreadcrumbsReportsIndexRoute:
      NavbarLayoutBreadcrumbsReportsIndexRoute,
    NavbarLayoutBreadcrumbsusersAgentsNewRoute:
      NavbarLayoutBreadcrumbsusersAgentsNewRoute,
    NavbarLayoutBreadcrumbsusersAgentsIndexRoute:
      NavbarLayoutBreadcrumbsusersAgentsIndexRoute,
  }

const NavbarLayoutBreadcrumbsRouteRouteWithChildren =
  NavbarLayoutBreadcrumbsRouteRoute._addFileChildren(
    NavbarLayoutBreadcrumbsRouteRouteChildren,
  )

interface NavbarLayoutRouteRouteChildren {
  NavbarLayoutBreadcrumbsRouteRoute: typeof NavbarLayoutBreadcrumbsRouteRouteWithChildren
  NavbarLayoutIndexRoute: typeof NavbarLayoutIndexRoute
}

const NavbarLayoutRouteRouteChildren: NavbarLayoutRouteRouteChildren = {
  NavbarLayoutBreadcrumbsRouteRoute:
    NavbarLayoutBreadcrumbsRouteRouteWithChildren,
  NavbarLayoutIndexRoute: NavbarLayoutIndexRoute,
}

const NavbarLayoutRouteRouteWithChildren =
  NavbarLayoutRouteRoute._addFileChildren(NavbarLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof NavbarLayoutBreadcrumbsRouteRouteWithChildren
  '/': typeof NavbarLayoutIndexRoute
  '/complaints': typeof NavbarLayoutBreadcrumbsComplaintsIndexRoute
  '/reports': typeof NavbarLayoutBreadcrumbsReportsIndexRoute
  '/agents/new': typeof NavbarLayoutBreadcrumbsusersAgentsNewRoute
  '/agents': typeof NavbarLayoutBreadcrumbsusersAgentsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof NavbarLayoutBreadcrumbsRouteRouteWithChildren
  '/': typeof NavbarLayoutIndexRoute
  '/complaints': typeof NavbarLayoutBreadcrumbsComplaintsIndexRoute
  '/reports': typeof NavbarLayoutBreadcrumbsReportsIndexRoute
  '/agents/new': typeof NavbarLayoutBreadcrumbsusersAgentsNewRoute
  '/agents': typeof NavbarLayoutBreadcrumbsusersAgentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_NavbarLayout': typeof NavbarLayoutRouteRouteWithChildren
  '/_NavbarLayout/_breadcrumbs': typeof NavbarLayoutBreadcrumbsRouteRouteWithChildren
  '/_NavbarLayout/': typeof NavbarLayoutIndexRoute
  '/_NavbarLayout/_breadcrumbs/complaints/': typeof NavbarLayoutBreadcrumbsComplaintsIndexRoute
  '/_NavbarLayout/_breadcrumbs/reports/': typeof NavbarLayoutBreadcrumbsReportsIndexRoute
  '/_NavbarLayout/_breadcrumbs/(users)/agents/new': typeof NavbarLayoutBreadcrumbsusersAgentsNewRoute
  '/_NavbarLayout/_breadcrumbs/(users)/agents/': typeof NavbarLayoutBreadcrumbsusersAgentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/complaints' | '/reports' | '/agents/new' | '/agents'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/' | '/complaints' | '/reports' | '/agents/new' | '/agents'
  id:
    | '__root__'
    | '/_NavbarLayout'
    | '/_NavbarLayout/_breadcrumbs'
    | '/_NavbarLayout/'
    | '/_NavbarLayout/_breadcrumbs/complaints/'
    | '/_NavbarLayout/_breadcrumbs/reports/'
    | '/_NavbarLayout/_breadcrumbs/(users)/agents/new'
    | '/_NavbarLayout/_breadcrumbs/(users)/agents/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NavbarLayoutRouteRoute: typeof NavbarLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  NavbarLayoutRouteRoute: NavbarLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_NavbarLayout"
      ]
    },
    "/_NavbarLayout": {
      "filePath": "_NavbarLayout/route.tsx",
      "children": [
        "/_NavbarLayout/_breadcrumbs",
        "/_NavbarLayout/"
      ]
    },
    "/_NavbarLayout/_breadcrumbs": {
      "filePath": "_NavbarLayout/_breadcrumbs/route.tsx",
      "parent": "/_NavbarLayout",
      "children": [
        "/_NavbarLayout/_breadcrumbs/complaints/",
        "/_NavbarLayout/_breadcrumbs/reports/",
        "/_NavbarLayout/_breadcrumbs/(users)/agents/new",
        "/_NavbarLayout/_breadcrumbs/(users)/agents/"
      ]
    },
    "/_NavbarLayout/": {
      "filePath": "_NavbarLayout/index.tsx",
      "parent": "/_NavbarLayout"
    },
    "/_NavbarLayout/_breadcrumbs/complaints/": {
      "filePath": "_NavbarLayout/_breadcrumbs/complaints/index.tsx",
      "parent": "/_NavbarLayout/_breadcrumbs"
    },
    "/_NavbarLayout/_breadcrumbs/reports/": {
      "filePath": "_NavbarLayout/_breadcrumbs/reports/index.tsx",
      "parent": "/_NavbarLayout/_breadcrumbs"
    },
    "/_NavbarLayout/_breadcrumbs/(users)/agents/new": {
      "filePath": "_NavbarLayout/_breadcrumbs/(users)/agents/new.tsx",
      "parent": "/_NavbarLayout/_breadcrumbs"
    },
    "/_NavbarLayout/_breadcrumbs/(users)/agents/": {
      "filePath": "_NavbarLayout/_breadcrumbs/(users)/agents/index.tsx",
      "parent": "/_NavbarLayout/_breadcrumbs"
    }
  }
}
ROUTE_MANIFEST_END */
